name: Daily Scrape Links

# This workflow will run once a day
on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 1:00 AM ET during Standard Time
    - cron: "0 5 * * *"  # Runs daily at 1:00 AM ET during Daylight Saving Time

  # Allows manual trigger if needed
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the scraping script
      - name: Run the scraping script
        run: |
          python scrape_links.py

      # Commit and Push changes
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the secret for authentication
        run: |
          # Configure Git author details
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add .
          git commit -m "Add daily scraped links"
          git push https://github.com/${{ github.repository }} HEAD:main
