name: Daily Scrape Links

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            curl \
            unzip \
            xvfb \
            libxi6 \
            libgconf-2-4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxrandr2 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libgbm1 \
            libnspr4 \
            libnss3 \
            libxcb1 \
            libxdamage1 \
            libxss1 \
            fonts-liberation \
            libappindicator3-1 \
            libindicator3-0.7 \
            xdg-utils \
            --no-install-recommends

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium chromedriver-autoinstaller

      - name: Run the scraping script
        run: |
          python scrape_links.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add daily scraped links"
          add: "scraped_links.md"