name: Daily Scrape

on:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraper
      run: |
        python scrape_links.py

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret for authentication
      run: |
        git add .
        git commit -m "Add daily scraped links"
        git push https://github.com/${{ github.repository }} HEAD:gh-pages  # Push to gh-pages or main, as necessary