name: Daily Scrape Links

# This workflow will run once a day
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

  # Allows manual trigger if needed
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the scraping script
      - name: Run the scraping script
        run: |
          python scrape_links.py

      # Commit and push the updated file with the scraped data
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add daily scraped links"
          add: "scraped_links.md"